### ISSUE TITLE
Does not work properly unless ESLint is a peer Dependency!

### ISSUE THREAD

**Issue by baer** [walmartlabs/eslint-config-defaults#30]

**Comment by ryan-roemer** [comment]
We could also investigate `process.env.PATH` mutation as a potential option as well to add to the documentation...

**Comment by baer** [comment]
Can you elaborate on that? This issue is specific to the following:

package.json
```
dependencies: {
  "eslint-config-defaults": "4.2.0"
}
```

```bash
eslint .
/Users/ebaer/.nvm/versions/node/v0.12.7/lib/node_modules/eslint/lib/config.js:171
                    throw e;
                          ^
Error: Cannot find module 'eslint-config-defaults/configurations/walmart/es5-browser'
Referenced from: /Users/ebaer/dev/walmart/tmp/.eslintrc
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at readConfigFromFile (/Users/ebaer/.nvm/versions/node/v0.12.7/lib/node_modules/eslint/lib/config.js:113:44)
    at loadConfig (/Users/ebaer/.nvm/versions/node/v0.12.7/lib/node_modules/eslint/lib/config.js:134:22)
    at /Users/ebaer/.nvm/versions/node/v0.12.7/lib/node_modules/eslint/lib/config.js:165:46
    at Array.reduceRight (native)
    at loadConfig (/Users/ebaer/.nvm/versions/node/v0.12.7/lib/node_modules/eslint/lib/config.js:149:36)
    at getLocalConfig (/Users/ebaer/.nvm/versions/node/v0.12.7/lib/node_modules/eslint/lib/config.js:273:23)
```

**Comment by baer** [comment]
Might be related to #16 actually.

**Comment by baodang** [comment]
Hi, I see this bug in 5.0.0 as well.

Using .eslintrc from README

```code
---
"extends":
  - "defaults/configurations/walmart/es6-browser"
```

will raise the error

```code
node_modules/eslint/lib/config.js:171
                    throw e;
                          ^
Error: Cannot find module 'eslint-config-defaults/configurations/walmart/es6-browser'
```

Does anyone have a workaround? Thanks

**Comment by baer** [comment]
@baodang Your issue is actually related to #33 which has been closed. You should be good to go on the latest.

**Comment by baer** [comment]
Closing this and documenting here: https://github.com/walmartlabs/eslint-config-defaults/issues/43

I'll update the README to reflect this known issue
